# Test API Requests for WAF Testing

### Normal GET request
GET http://localhost:3000/api/test
Accept: application/json

### Normal POST request
POST http://localhost:3000/api/test
Content-Type: application/json

{
  "message": "Hello, World!"
}

### SQL Injection Test
GET http://localhost:3000/api/users?id=1 OR 1=1
Accept: application/json

### XSS Test
POST http://localhost:3000/api/comments
Content-Type: application/json

{
  "comment": "<script>alert('XSS')</script>"
}

### Path Traversal Test
GET http://localhost:3000/api/files?path=../../../etc/passwd
Accept: application/json

### Command Injection Test
POST http://localhost:3000/api/execute
Content-Type: application/json

{
  "command": "ls; rm -rf /"
}

### Rate Limiting Test (Run multiple times quickly)
GET http://localhost:3000/api/stress-test
Accept: application/json